name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: lukka/get-cmake@latest
      with:
        useLocalCache: true
        useCloudCache: false
        
    - name: make
      run: |
        cmake . -B build
        cmake --build build --config Release -j

    - uses: actions/upload-artifact@v4
      with:
        name: release
        path: Release
