name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Submodule
    - run: git submodule update --init --recursive
    
    - uses: actions/checkout@v4
    
    - uses: lukka/get-cmake@latest
    
    - uses: humbletim/install-vulkan-sdk@v1.2
        
    - name: make
      run: |
        cmake . -B build
        cmake --build build --config Release -j

    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: build
