name: Build vkraygs on Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvulkan-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev wayland-protocols libwayland-dev libxkbcommon-dev glslang-tools
    - name: Install CUDA toolkit
      run: |
        sudo apt-get install -y nvidia-cuda-toolkit
    - name: Configure CMake
      run: cmake . -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --parallel
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: vkraygs-binaries
        path: build
