name: Build and Release vkraygs on Windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies with Chocolatey
      run: |
        choco install -y cmake ninja
      shell: cmd

    - name: Install Vulkan SDK
      run: |
        curl -L -o vulkan-sdk.exe "https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe"
        .\vulkan-sdk.exe /S
        dir C:\VulkanSDK
      shell: cmd

    - name: Set up Visual Studio environment
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '17'  # Visual Studio 2022

    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DVULKAN_SDK="C:\VulkanSDK\1.3.275.0"
      shell: cmd

    - name: Build
      run: |
        cmake --build build --parallel
      shell: cmd

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vkraygs-binaries
        path: build/vkgs_viewer.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/vkgs_viewer.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
